### ISSUE TITLE
Create Hugo Module for componentizing Netlify CMS config file.

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/netlify-cms#3]
Phase 1

- Base File living at `data/netlifycms/base.yaml` with the root config (`site_url` etc...`)
- Collections files living at `data/netlifycms/collections/posts.yaml`
- Have sensible default settings in the Module which project could overwrtite.

Phase 2

- Add reusable fields to `data/netlifycms/fields/title.yaml`
- Add an "import" keyword so basic fields can be reusable throughout collections

```yaml
# data/netlifycms/fields/title.yaml
label: "Title"
name: "title"
widget: "string"
```

```yaml
#data/netlifycms/collections/posts
fields:
  - import title
  - { label: "Last Name", name: "name_last", widget: "string" }
  [ ... ]
```

We'll use `aaldef` netlify branch to test/compare results.

This could be a great opensource module to promote TND.
